# Generated by Django 3.2.3 on 2021-05-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=25)),
                ('team_logo', models.FileField(blank=True, null=True, upload_to='media/')),
                ('club_state', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('player_image', models.ImageField(upload_to='', verbose_name='media/')),
                ('jersey_number', models.IntegerField()),
                ('matches', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('highest', models.IntegerField()),
                ('half_centuries', models.IntegerField()),
                ('centuries', models.IntegerField()),
                ('ipl_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl.team')),
            ],
        ),
    ]
