# Generated by Django 3.2.3 on 2021-05-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
