# Generated by Django 3.2.3 on 2021-05-17 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0002_auto_20210516_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='points',
            fields=[
                ('points_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('played', models.IntegerField()),
                ('won', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('tied', models.IntegerField()),
                ('points', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('team1_score', models.CharField(blank=True, max_length=50, null=True)),
                ('team2_score', models.CharField(blank=True, max_length=50, null=True)),
                ('team1_overs', models.CharField(blank=True, max_length=50, null=True)),
                ('team2_overs', models.CharField(blank=True, max_length=50, null=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='ipl.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='ipl.team')),
            ],
        ),
    ]
