# Generated by Django 3.2.3 on 2021-05-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0005_alter_match_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='points_id',
        ),
        migrations.AddField(
            model_name='points',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
