# Generated by Django 3.2.3 on 2021-05-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0006_auto_20210517_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points',
            name='tied',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
