# Generated by Django 3.2.3 on 2021-05-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0007_auto_20210517_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
