# Generated by Django 3.2.3 on 2021-05-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0009_auto_20210518_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(unique=True),
        ),
    ]
