# Generated by Django 3.2.3 on 2021-05-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0010_alter_match_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_id',
        ),
    ]
