# Generated by Django 3.2.3 on 2021-05-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0011_remove_match_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='tied',
        ),
    ]
